modulecaller_source_region = "us-east-1"
modulecaller_assume_role_deployer_account = "arn:aws:iam::176540105868:role/assume-capterra-admin-batch"
vertical = "capterra"
application = "autobidder"
environment = "prod"
namespace = "team-frodo"
